In [1]:
import numpy as np
import pandas as pd

In [37]:
a = np.array([[0, 1, 0],
              [1, 0, 0.7],
              [0, 0.7, 0]])

b = np.array([[0, 1, 1],
              [1, 0, 0.7],
              [1, 0.7, 0]])

c = np.array([[0, 1, 0.5],
              [1, 0, 0.7],
              [0.5, 0.7, 0]])

d = np.array([[0, 1, -0.5],
              [1, 0, 0.7],
              [0.5, 0.7, 0]])

In [31]:
Z = np.exp(-1 * 1 * c)
Z

array([[1.        , 0.36787944, 0.60653066],
       [0.36787944, 1.        , 0.4965853 ],
       [0.60653066, 0.4965853 , 1.        ]])

In [32]:
denom = Z.sum(axis=1)
denom

array([1.9744101 , 1.86446474, 2.10311596])

In [33]:
eps = 1e-15
denom = np.maximum(denom, eps)
denom

array([1.9744101 , 1.86446474, 2.10311596])

In [34]:
spread = float((1.0 / denom).sum())

print(spread)

1.518312307483551


In [43]:
print(d)

if np.any(d < 0):
    raise ValueError("Matrix contains negative values.")

[[ 0.   1.  -0.5]
 [ 1.   0.   0.7]
 [ 0.5  0.7  0. ]]


ValueError: Matrix contains negative values.